licenses(["notice"])

py_library(
    name = "pose_body",
    srcs = ["pose_body.py"],
    srcs_version = "PY3",
    visibility = ["//visibility:public"],
    deps = [
        "//third_party/py/numpy",
        "//:pose_body",
        "//:pose_header",
        "//torch:pose_body",
        "//utils:reader",
        "//third_party/py/scipy",
        "//third_party/py/torch:pytorch",
    ],
)
