/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { PoseModel } from "pose-format/dist/types";
export { PoseModel } from "pose-format/dist/types";
export namespace Components {
    interface PoseViewer {
        /**
          * @default null
         */
        "aspectRatio": number;
        /**
          * @default true
         */
        "autoplay": boolean;
        /**
          * @default null
         */
        "background": string;
        /**
          * @default NaN
         */
        "currentTime": number;
        /**
          * @default NaN
         */
        "duration": number;
        /**
          * @default false
         */
        "ended": boolean;
        "getPose": () => Promise<PoseModel>;
        /**
          * @default null
         */
        "height": string;
        /**
          * @default false
         */
        "loop": boolean;
        "nextFrame": () => Promise<void>;
        /**
          * @default null
         */
        "padding": string;
        "pause": () => Promise<void>;
        /**
          * @default true
         */
        "paused": boolean;
        "play": () => Promise<void>;
        /**
          * @default 1
         */
        "playbackRate": number;
        /**
          * @default 0
         */
        "readyState": number;
        /**
          * @default 'canvas'
         */
        "renderer": 'canvas' | 'svg' | 'interactive';
        "src": string | Buffer;
        "syncMedia": (media: HTMLMediaElement) => Promise<void>;
        /**
          * @default null
         */
        "thickness": number;
        /**
          * @default null
         */
        "width": string;
    }
}
export interface PoseViewerCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPoseViewerElement;
}
declare global {
    interface HTMLPoseViewerElementEventMap {
        "canplaythrough$": void;
        "ended$": void;
        "loadeddata$": void;
        "loadedmetadata$": void;
        "loadstart$": void;
        "pause$": void;
        "play$": void;
        "firstRender$": void;
        "render$": void;
    }
    interface HTMLPoseViewerElement extends Components.PoseViewer, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPoseViewerElementEventMap>(type: K, listener: (this: HTMLPoseViewerElement, ev: PoseViewerCustomEvent<HTMLPoseViewerElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPoseViewerElementEventMap>(type: K, listener: (this: HTMLPoseViewerElement, ev: PoseViewerCustomEvent<HTMLPoseViewerElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPoseViewerElement: {
        prototype: HTMLPoseViewerElement;
        new (): HTMLPoseViewerElement;
    };
    interface HTMLElementTagNameMap {
        "pose-viewer": HTMLPoseViewerElement;
    }
}
declare namespace LocalJSX {
    interface PoseViewer {
        /**
          * @default null
         */
        "aspectRatio"?: number;
        /**
          * @default true
         */
        "autoplay"?: boolean;
        /**
          * @default null
         */
        "background"?: string;
        /**
          * @default NaN
         */
        "currentTime"?: number;
        /**
          * @default NaN
         */
        "duration"?: number;
        /**
          * @default false
         */
        "ended"?: boolean;
        /**
          * @default null
         */
        "height"?: string;
        /**
          * @default false
         */
        "loop"?: boolean;
        "onCanplaythrough$"?: (event: PoseViewerCustomEvent<void>) => void;
        "onEnded$"?: (event: PoseViewerCustomEvent<void>) => void;
        "onFirstRender$"?: (event: PoseViewerCustomEvent<void>) => void;
        "onLoadeddata$"?: (event: PoseViewerCustomEvent<void>) => void;
        "onLoadedmetadata$"?: (event: PoseViewerCustomEvent<void>) => void;
        "onLoadstart$"?: (event: PoseViewerCustomEvent<void>) => void;
        "onPause$"?: (event: PoseViewerCustomEvent<void>) => void;
        "onPlay$"?: (event: PoseViewerCustomEvent<void>) => void;
        "onRender$"?: (event: PoseViewerCustomEvent<void>) => void;
        /**
          * @default null
         */
        "padding"?: string;
        /**
          * @default true
         */
        "paused"?: boolean;
        /**
          * @default 1
         */
        "playbackRate"?: number;
        /**
          * @default 0
         */
        "readyState"?: number;
        /**
          * @default 'canvas'
         */
        "renderer"?: 'canvas' | 'svg' | 'interactive';
        "src"?: string | Buffer;
        /**
          * @default null
         */
        "thickness"?: number;
        /**
          * @default null
         */
        "width"?: string;
    }
    interface IntrinsicElements {
        "pose-viewer": PoseViewer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "pose-viewer": LocalJSX.PoseViewer & JSXBase.HTMLAttributes<HTMLPoseViewerElement>;
        }
    }
}
