py_library(
    name = "pose_body",
    srcs = ["pose_body.py"],
	srcs_version = "PY3",
    deps = [
    	"//:pose_header",
    	"//:pose_body",
    	"//torch:pose_body",
    	"//utils:reader",
        "//third_party/py/scipy",
        "//third_party/py/torch",
        "//third_party/py/numpy"
    ],
    visibility = ["//visibility:public"]
)